### ISSUE TITLE
Only works if I type "http://go/________"

### ISSUE THREAD

**Issue by kblestarge** [sonythomas82/shortie#2]
It should also work with "https://go/_______" because my chrome browser is defaulting to that, which takes me to a google search for "go/jira" for example.

![image](https://user-images.githubusercontent.com/11730298/100900123-1fe17d00-3488-11eb-9fdb-3b0086fad74f.png)

**Comment by sonythomas82** [comment]
select go/jira website option 
![image](https://user-images.githubusercontent.com/12157167/101300312-c9af6980-37fa-11eb-8c90-ead2098120d6.png)

**Comment by sonythomas82** [comment]
Select website option from the suggestion list. Refer the screenshot on the previous comment.
